### ISSUE TITLE
Tier 2 Requirements

### ISSUE THREAD

**Issue by shaylew** [2001-man-display-none/Grace-Potter-Shop#56]
### As a customer, I want to be able to:
- [x] see all products that belong to a certain category. #67
  - *Keep this simple. For example, a product can only belong to one category.*
- [ ] explore an aesthetically pleasing website so I can easily navigate around and enjoy the experience (UI/UX).
  - *This includes front-end data validations. For example, if certain fields of a form are required and must be in a specific format, this is obvious to the user.*
  - [x] have a generally readable and clean style #62 
  - [ ] do front-end data validation on the login and signup pages
- [x] have a persistent cart so I can revisit and pick up where I left off.
  - *There are two more experiences to consider here. Explore your favorite websites to see what the intended behavior is for the following cases:*
    - [x] **Guest-only:** I don't want to create an account, but I want my cart to persist between browser refreshes.
      - Look into front-end storage for this one.
    - [x] **Guest-to-logged-in-user:** Initially, I'm not logged in, and I add items to my cart. When I eventually log in, I want to see those same items I added when I was logged in still in my cart, in addition to the items I may have had in my cart from a previous logged in session.

### As a logged-in customer, I want to be able to:
- [ ] see my order history so I can remember my previously purchased items and their prices at the time of purchase. #65
  - **partial**: price at time of purchase is not saved
- [x] view and edit my user profile so I can update my information when necessary. #66
- [ ] log in through third-party authentication so I can avoid creating an account specific to the website.
  - *For example, Google OAuth.*

### As an administrator, I want to be able to:
- [ ] allow customers to have a variety of payment method options in order to increase checkout conversion.
  - *Begin by integrating Stripe, and, if interested, dive into integrating PayPal, Venmo, Braintree, or Bitcoin.*
- [ ] edit products and manage users through a dashboard so I can easily make changes and assessments as necessary.

### As an engineer, I want:
- [ ] [continuous integration and delivery (deployment)](https://www.atlassian.com/continuous-delivery/continuous-integration) of the codebase so that there are lower rates of release failure.
